export default function Projects(){
  const projects = [
    { title:'YANKOMAS', label:'Layanan Pengaduan Imigrasi', category:'WEB DEVELOPMENT', desc:'Mengembangkan website layanan pengaduan imigrasi saat magang di Kantor Imigrasi Kelas I TPI Bandung.', tech:['HTML','CSS','JavaScript'], github:'https://github.com/handi18/YANKOMAS.git', demo:'https://yankomas.infinityfree.io/?i=1', tone:'lime' },
    { title:'Website BUMDES Desa Hanura', category:'WEB DEVELOPMENT', desc:'Mengembangkan website BUMDES Desa Hanura saat kegiatan KKN sebagai media informasi dan digitalisasi layanan desa.', tech:['HTML','CSS','JavaScript','WordPress'], github:'https://github.com/desahanura/website-bumdes', demo:'https://bumdes.desahanura.id/', tone:'purple' },
    { title:'Website WordPress Desa Hanura', category:'CMS DEVELOPMENT', desc:'Membangun website desa berbasis WordPress untuk mendukung publikasi informasi dan dokumentasi kegiatan desa selama KKN.', tech:['WordPress','Elementor'], github:'https://github.com/desahanura/website-bumdes', demo:'https://desahanura.id/', tone:'orange' },
    { title:'Game Project — Pemrograman Berorientasi Objek', category:'GAME DEVELOPMENT', desc:'Mengembangkan game sebagai project mata kuliah dengan menerapkan konsep OOP.', tech:['Java','OOP'], github:'https://github.com/gusti06/TUBES-PBO-GAME', demo:'', tone:'lime' },
    { title:'GlycoAI — Deteksi Risiko Diabetes', category:'KECERDASAN KOMPUTASIONAL', desc:'Tugas besar mata kuliah Kecerdasan Komputasional: web untuk deteksi risiko diabetes dan monitoring pasien diabetes.', tech:['Python','Flask','TensorFlow','JavaScript','HTML','CSS'], github:'https://github.com/gusti06/Tubes-KK_GlycoAI', demo:'', tone:'purple' },
    { title:'SmartMatch — Rekomendasi Laptop', category:'KECERDASAN KOMPUTASIONAL', desc:'Tugas besar Kecerdasan Komputasional: sistem rekomendasi pembelian laptop menggunakan metode pembelajaran mesin.', tech:['Python','scikit-learn','Flask','JavaScript','HTML','CSS'], github:'https://github.com/gusti06/Tubes-KK-SmartMatch', demo:'', tone:'orange' },
    { title:'MageArena', category:'GAME DEVELOPMENT', desc:'Project game berbasis arena untuk menampilkan pengembangan gameplay, logika permainan, dan interaksi pengguna.', tech:['Game Development','JavaScript'], github:'https://github.com/gusti06/MageArena', demo:'', tone:'purple' }
  ]
  return <section id="projects" className="content-section projects-section" data-aos="fade-up"><div className="section-heading"><p className="section-kicker">03 / PROJECTS</p><h2>SELECTED <span>WORK</span></h2><p className="section-note">Beberapa proyek utama yang saya kerjakan, mulai dari tugas besar kecerdasan komputasional sampai project web dan game.</p></div><div className="project-grid">{projects.map((project,index)=><article key={project.title} className={`project-card ${index===0?'project-featured':''} tone-${project.tone}`}><div className="project-top"><span className="mono">PROJECT_{String(index+1).padStart(3,'0')}</span><span className="mono">{project.category}</span></div><h3>{project.title}</h3>{index===0&&<div className="project-stamp">FEATURED<br />001</div>}<p>{project.desc}</p><div className="tag-row">{project.tech.map(tech=><span key={tech}>{tech}</span>)}</div><div className="project-links"><a href={project.github} target="_blank" rel="noreferrer">VIEW GITHUB ↗</a>{project.demo?<a href={project.demo} target="_blank" rel="noreferrer">LIVE DEMO ↗</a>:<span>NO DEMO</span>}</div></article>)}</div></section>
}
